---
site_name: Experimental Platform for Edge Computing Applications &#8212; ExPECA
theme: 
  palette:
    scheme: default
    primary: indigo
    accent: amber
  logo: assets/kth_logo.png
  name: material
  font:
    text: Ubuntu
    code: JetBrains Mono
  icon:
    # logo: fontawesome/solid/server
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
repo_url: https://github.com/KTH-EXPECA/kth-expeca.github.io
repo_name: KTH-EXPECA/kth-expeca.github.io
copyright: Copyright &copy; 2020 - EXPECA Project Group at KTH Royal Institute of Technology
markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: yes
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: 🔗
plugins:
  - awesome-pages
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      fallback_to_build_date: true
...