---
site_name: ExPECA
extra_css:
  - stylesheets/extra.css
theme: 
  palette:
    scheme: default
    primary: indigo
    accent: amber
  logo: assets/kth_logo.png
  name: material
  custom_dir: overrides
  font:
    text: Ubuntu
    code: JetBrains Mono
  icon:
    # logo: fontawesome/solid/server
    repo: fontawesome/brands/github
    admonition: {}
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
copyright: Copyright &copy; 2023 - EXPECA Project Group at KTH Royal Institute of Technology
markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: yes
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - toc:
      permalink: 🔗
plugins:
  - meta
  - blog:
      blog_dir: .
      archive: false
      categories: false
  - tags
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      fallback_to_build_date: true
nav:
  - Home: index.md
  - Getting started: start.md
  - Hardware discovery: inventory.md
  - About: about.md
...