# docker login -u kth-expeca -p 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 ghcr.io
# docker pull ghcr.io/kth-expeca/mkdocs-material-insiders

FROM ghcr.io/kth-expeca/mkdocs-material-insiders
RUN pip install mkdocs-awesome-pages-plugin mkdocs-git-revision-date-localized-plugin mkdocs-meta-descriptions-plugin
