# automatically deploys the documentation on github pages
---
name: ci 
on:
  push:
    branches: 
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kth-expeca/mkdocs-material-insiders
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: mkdocs gh-deploy --force
...

